server:
  port: 8888

spring:
  datasource:
    username: root
    password: Hsc18501228193 #hoj123456
    url:  jdbc:mysql://localhost:3306/transaction_2019011192?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC #123.56.235.159:3308
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.srx.transaction.Entities


logging:
  level:
    com: debug
    org.springframework: warn
